### ISSUE TITLE
Saturation

### ISSUE THREAD

**Issue by kochd** [vn971/linux-color-inversion#6]
GLSL seams to be able to over/under-saturate textures. However i have no clue how to write a GLSL for compton. Could you help me out? 

This might be helpful: 

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/saturation.glsl

**Comment by vn971** [comment]
Closing as it's not an issue of this project.

On the positive side, yeah, it's easy enough so I can try to write a fix. This could work:
```
uniform bool invert_color;
uniform float opacity;
uniform sampler2D tex;

void main() {
	vec4 c = texture2D(tex, gl_TexCoord[0].st);
	if (invert_color) {
		int mult = 1.3;
		int shift = (1 - mult) / 2;
		c = vec4(c.a + c.r*mult + shift, c.a + c.g*mult + shift, c.a + c.b*mult + shift, c.a);
	}
	c *= opacity;
	gl_FragColor = c;
}
```

Also, maybe some simpler non-compton solutions could exist. `xrandr` doesn't unfortunately let you out of 0..100 percentage, but maybe some other tools allow that. And sometimes just increasing monitory-s saturation works as well.:)
