### ISSUE TITLE
Thanks + Red shift

### ISSUE THREAD

**Issue by JZL** [vn971/linux-color-inversion#8]
Hi,

I wanted to thank you for making this program! I was use a janky self-built glsl file which just set to black and white and then inverted. This is much nicer :)

Also, just something I found helpful but I [combined this with a red-shift color temperature adjustment](https://github.com/JZL/linux-color-inversion/blob/master/red_shift_whiteish.glsl) so even for originally-dark-now-light sections, it hurts my eyes even less. 

I can also comment on #3 but I'm curious, how would you make the colors darker? A negative white-bias (it looked weird when I tried that)?

Thanks!

**Comment by vn971** [comment]
Wow, that's a complex script. I wonder if it can be simplified (by a factor) for our specific case. Then again I'm not sure I have the energy to do that at the moment TBH, and if the script works well, it's good as it is.:)

> how would you make the colors darker?

That's a good question. I think one should be able to adapt the current script with two constants, e.g. `WHITE_BIAS` and `BLACK_BIAS`. And anyone interested could thus be able to experiment with the settings they want. I think I might reopen that linked issue and ask for contributors ("help wanted").

**Comment by vn971** [comment]
I've reopened the referenced issue. I'm a bit under-motivated to make the change myself as my current setup is kinda working for me. But I'd be happy to merge a PR with a general solution to the problem!
